name: OmniRoute
version: 3.8.46
slug: omniroute
description: Free AI Gateway - one endpoint, 250+ providers
url: https://github.com/diegoasanch/omniroute
arch:
- amd64
- armv7
- aarch64
ports:
  20128/tcp: 20128
map:
- data:rw
options:
  omniroute_memory_mb: 1024
schema:
  omniroute_memory_mb: int
